"""Initial migration.

Revision ID: 28f02d8adf2e
Revises: 77616a77a137
Create Date: 2020-02-21 18:52:16.736683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f02d8adf2e'
down_revision = '77616a77a137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('datetime', sa.String(length=16), nullable=True),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('pos', sa.String(length=128), nullable=True),
    sa.Column('pron', sa.String(length=128), nullable=True),
    sa.Column('mon', sa.String(length=256), nullable=True),
    sa.Column('example_pron', sa.String(length=256), nullable=True),
    sa.Column('example', sa.String(length=256), nullable=True),
    sa.Column('example_mon', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
